// eslint-disable-next-line @nx/enforce-module-boundaries
import '../../../libs/ui/src/styles/globals.css';

export const metadata = {
  title: 'Welcome to docs',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
